### PR TITLE
Update `scipy-notebook:hub` base image

### PR DESCRIPTION
**Pull request by BearBearCodes**
Update base image from `scipy-notebook:hub-2.0.1` (which ran Python 3.9) to the latest `scipy-notebook:hub` image (`5.2.1`)

### CODE REVIEW

**Comment by BearBearCodes** [comment]
@Dhananjhay Can you check if this fixes the issue of a blank terminal on the CANFAR Science Portal?

**Comment by Dhananjhay** [comment]
I was able to successfully run a terminal inside the Docker container using `scipy-notebook:hub-5.2.1`. However, there are a few changes and suggestions we should be mindful of before proceeding.

Upgrading the base image from `scipy-notebook:hub-2.0.1` (which used Python v3.9) to `scipy-notebook:hub-5.2.1` (which uses Python v3.12) introduces some breaking changes:

 1. We need to revert to older versions of the notebook because nbextensions are incompatible with version 7, which comes with the latest version of scipy-notebook:hub-5.2.1.
 2. Additionally, we should use an older version of SciPy because the simpson method from scipy.integrate in v1.14.1, which comes with the new SciPy notebook image, no longer accepts the even parameter, breaking the ETC tool.
 3. These version pinning adjustments are necessary to build the Docker image and run an example notebook: [ETC Notebook Example](https://github.com/CASTOR-telescope/ETC_notebooks/blob/master/snr_table.ipynb). I only ran one example notebook as a test case, but I suspect there may be other lingering changes or updates that could break the ETC tool when used at full capacity. I believe we should inspect these with further scrutiny before pushing to CANFAR.

**Comment by BearBearCodes** [comment]
Hi Dhananjhay,

Thank you for testing. I agree with you that we should get these issues resolved before pushing to CANFAR—I will have to re-setup my testing environment and re-learn how to configure Docker since I got a new laptop earlier this year, which I was secretly hoping could be avoided.

I can take care of the necessary updates to the `castor_etc` Python package, but you are also free to contribute if you want. For instance, I'll remove the `even` parameter when we use `scipy.integrate.simpson()`.

I'll also check out which versions of `scipy-notebook:hub` are compatible with `nbextensions`. I believe we need `nbextensions` to use `ipyevents`, which makes `ipywidgets` images clickable and interactive. Please correct me if I am mistaken, though.

Can't give an ETA for when these changes will be done because I'm not sure how long troubleshooting the various issues (and even just the number of issues there are) will take...

**Comment by BearBearCodes** [comment]
Oops I just realized you made some changes that will fix the current issues you noted. Still, I will check some other notebooks (i.e., the super-outdated [Getting Started notebook](https://github.com/CASTOR-telescope/ETC_notebooks/blob/master/getting_started_photometry.ipynb)) to make sure everything is working well before pushing to CANFAR. Thanks Dhananjhay!

**Comment by BearBearCodes** [comment]
Hi @Dhananjhay, thanks for your work on this. I've removed all instances of the `even` parameter in `scipy.integrate.simpson()` calls so `castor_etc` will work with the newest version of scipy. I ran the [getting_started_photometry](https://github.com/CASTOR-telescope/ETC_notebooks/blob/4369994f398cb49eb590db3627fc2d76566b5d40/getting_started_photometry.ipynb) and [snr_table](https://github.com/CASTOR-telescope/ETC_notebooks/blob/4369994f398cb49eb590db3627fc2d76566b5d40/snr_table.ipynb) notebooks on CANFAR and checked that these notebooks—as well as the JupyterLab terminal—all work.

I'll merge this PR now. If you find any problems, feel free to open an issue.

**Comment by Dhananjhay** [comment]
Awesome! Thanks for you swift response and hardwork on resolving this issue as soon as possible @BearBearCodes

**Pull request merged**
